### PR TITLE
Baidu Location Provider

### PR DESCRIPTION
**Pull request by abkaplan07**
A `LocationProvider` which uses Baidu's Location Services to provide GPS coordinates.

Baidu's SDK documentation for location services can be found [here](http://lbsyun.baidu.com/index.php?title=android-locsdk). The SDK documents are in Chinese, but Google does a decent enough job translating.

To actually use this in a production app, you need to procure a Baidu API key and add it to your application's manifest.  By default the provider initializes the Baidu SDK, but this can be overridden.

### CODE REVIEW

**Comment by abkaplan07** [comment]
DO NOT MERGE THIS IN YET!
The behavior of Baidu's SDK initializer is not idempotent. It will only run the broadcast receiver once (per our testing). I need to refactor this out and document that the Baidu SDK must be initialized and verified prior to use.

**Comment by abkaplan07** [comment]
Closing - not ready for prime time just yet.

**Comment by mrmans0n** [comment]
Yeah, and also one big issue here: forcing the users to have baidu dependencies (when most of them aren´t going to use them anyway) would feel pretty bad. I´d rather go the "extension library" route with this when going forward.

**Comment by abkaplan07** [comment]
Makes sense re the extension library route. We may need to refactor some of the `LocationProvider` interface to get Baidu's initialization code to work properly.

**Pull request closed without merging**
