### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jvartanian94**
Set gradle transitive property to false to prevent multiple instances
of ‘com.google.android.gms’

Fixes issue #30

### CODE REVIEW

**Comment by mrmans0n** [comment]
Thank you @jvartanian94, though I'd prefer to leave the dependency as it is (because it's really simple and you shouldn't need more than that). 

But as it's a fairly common problems some users could have, I think it should be commented afterwards, with something like: "If you are having problems importing the library, because you are using google play services in your project or other dependency is, you should use..."

What do you think?

Thanks!

**Comment by jvartanian94** [comment]
@mrmans0n Does this issue not affect you?

**Comment by mrmans0n** [comment]
Nope, in the projects I've used this library it's the only play services location dependency I am using. 

You could see it with the sample module. It's using the current dependency and works perfectly. That's why I'm saying this won't happen to all users, just the ones that are already using other stuff from the play services to cause the collision.

**Comment by mrmans0n** [comment]
Great! Thanks

**Comment by setu1421** [comment]
I am facing this issue and i have google play service plus google maps utils library.I have tried to include {transitive = false;} but the error remains. you can see it also it SO:
http://stackoverflow.com/questions/29949276/how-to-solve-2-libraries-with-same-package-name-in-my-dependencies-in-android-st

**Pull request merged**
